"""Create Tenant

Revision ID: 845eedbf5e36
Revises: None
Create Date: 2016-06-10 12:30:30.103000

"""

# revision identifiers, used by Alembic.
revision = '845eedbf5e36'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant')
    ### end Alembic commands ###